### ISSUE TITLE
Milestone: Alpha

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/api.webmaker.org#1]
See planning ticket: https://github.com/MozillaFoundation/plan/issues/427

Review: 
 - Intro deck: http://bit.ly/webmaker-intro
 - Build deck: http://bit.ly/webmaker-build 
 - [Services Q&A etherpad](https://etherpad.mozilla.org/servicetechquestionswebmaker)
 - [Roadmap](https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1ZvdNJLHuW0fIBt_-WcR7Ns6OhZgaMy6MI9kfjlXF-9o/edit#gid=0
)

Tasks: 
 - [x] List deliverables for this heartbeat as comments on this issue.
 - [x] Transform the useful info from the noisy etherpad above into spreadsheets or diagrams.
 - [x] File a series of questions that need answers in order to plan and implement services for Webmaker.

cc @thisandagain @secretrobotron

**Comment by xmatthewx** [comment]
We reviewed the [readme](https://github.com/mozilla/api.webmaker.org/blob/master/README.md). @cadecairos will file issues for sections of the plan to delivered at the end of this heartbeat. 

cc @wex @thisandagain @jbuck

**Comment by thisandagain** [comment]
Tracking remaining tasks in "Alpha" milestone
